
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Google_Sans, Source_Code_Pro } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";

import { SessionProvider } from "next-auth/react";
import Providers from "./provider";
import { ThemeProvider } from "@/components/themes/theme-provider";
import { ModeToggle } from "@/components/themes/toogle-theme";

const google_sans = Google_Sans({
  subsets: ["latin"],
  variable: "--font-googleSans"
  
})

const source_code_pro = Source_Code_Pro({
  subsets: ["latin"],
  variable: "--font-souceCodePro"
})




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`  ${google_sans.className}  antialiased`}
        suppressHydrationWarning
      >
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            
            
            {children}
            
          </ThemeProvider>
          
        </Providers>
      </body>
    </html>
  );
}
